#pragma once
#include "rc_epoch_protocol.h"

ComPtr<ID3D12Resource> RcSharedStaging(ID3D12Device* device,uint64_t bytes,D3D12_HEAP_TYPE type,D3D12_RESOURCE_STATES state) {
    D3D12_RESOURCE_DESC desc{}; desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER; desc.Width=bytes; desc.Height=1; desc.DepthOrArraySize=1; desc.MipLevels=1; desc.SampleDesc.Count=1; desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    D3D12_HEAP_PROPERTIES heap{}; heap.Type=type; ComPtr<ID3D12Resource> result;
    Require(SUCCEEDED(device->CreateCommittedResource(&heap,D3D12_HEAP_FLAG_NONE,&desc,state,nullptr,IID_PPV_ARGS(&result))),"RC shared path staging creation failed"); return result;
}

int RcSharedPathChild(ffxFunctions& api,ID3D12Device* device,uint64_t provider,bool wave32,const std::array<uint64_t,13>& values,LUID actualLuid) {
    const LUID expected{DWORD(values[6]),LONG(uint32_t(values[7]))}; Require(actualLuid.LowPart==expected.LowPart&&actualLuid.HighPart==expected.HighPart,"RC shared path adapter LUID mismatch");
    UINT inferenceCount=UINT(values[8]),trainingCount=UINT(values[9]); const UINT batches=UINT(values[10]),budgetMiB=UINT(values[11]),epochs=UINT(values[12]); const bool discoverCounts=!inferenceCount&&!trainingCount;
    Require((discoverCounts||(inferenceCount&&inferenceCount<=InferenceSamples&&trainingCount&&trainingCount<=TrainingSamples))&&batches>=1&&batches<=2&&budgetMiB>=1&&budgetMiB<=256&&epochs>=1&&epochs<=4,"RC shared path counts invalid");
    constexpr uint64_t sizes[5]={sizeof(RcCacheInput)*InferenceSamples,sizeof(RcCacheOutput)*InferenceSamples,sizeof(RcCacheInput)*TrainingSamples,sizeof(RcCacheOutput)*TrainingSamples,sizeof(uint32_t)*2};
    constexpr uint32_t strides[5]={sizeof(RcCacheInput),sizeof(RcCacheOutput),sizeof(RcCacheInput),sizeof(RcCacheOutput),sizeof(uint32_t)}; std::array<RcExternalBuffer,5> buffers;
    for(UINT i=0;i<5;++i) { Require(SUCCEEDED(device->OpenSharedHandle(HANDLE(uintptr_t(values[i])),IID_PPV_ARGS(&buffers[i].gpu))),"RC shared path resource open failed"); buffers[i].bytes=sizes[i]; buffers[i].stride=strides[i]; const auto desc=buffers[i].gpu->GetDesc();
        Require(desc.Dimension==D3D12_RESOURCE_DIMENSION_BUFFER&&desc.Width==sizes[i]&&(desc.Flags&D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),"RC shared path resource mismatch"); }
    ComPtr<ID3D12Fence> sharedFence; Require(SUCCEEDED(device->OpenSharedHandle(HANDLE(uintptr_t(values[5])),IID_PPV_ARGS(&sharedFence))),"RC shared path fence open failed");
    const uint64_t budgetBytes=uint64_t(budgetMiB)*1024*1024; ffxOverrideVersion version{}; version.header.type=FFX_API_DESC_TYPE_OVERRIDE_VERSION; version.versionId=provider; RcGpuBudget tracked(device,budgetBytes,0);
    ffxCreateBackendDX12AllocationCallbacksDesc callbacks{}; callbacks.header.type=FFX_API_CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12_ALLOCATION_CALLBACKS; callbacks.pfnFfxResourceAllocator=RcGpuBudget::Resource; callbacks.pfnFfxResourceDeallocator=RcGpuBudget::FreeResource; callbacks.pfnFfxHeapAllocator=RcGpuBudget::Heap; callbacks.pfnFfxHeapDeallocator=RcGpuBudget::FreeHeap; callbacks.header.pNext=&version.header;
    ffxCreateBackendDX12Desc backend{}; backend.header.type=FFX_API_CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12; backend.device=device; backend.header.pNext=&callbacks.header;
    auto create=[&](uint32_t flags,ffxContext& context) { ffxCreateContextDescRadianceCache desc{}; desc.header.type=FFX_API_CREATE_CONTEXT_DESC_TYPE_RADIANCECACHE; desc.header.pNext=&backend.header; desc.flags=flags; desc.version=FFX_RADIANCECACHE_VERSION; desc.maxInferenceSampleCount=InferenceSamples; desc.maxTrainingSampleCount=TrainingSamples; return api.CreateContext(&context,&desc.header,nullptr); };
    ffxContext context{}; auto createCode=create(FFX_RADIANCE_CACHE_CONTEXT_TRY_FORCE_WMMA,context); if(createCode==FFX_API_RETURN_ERROR_PARAMETER&&wave32&&!tracked.live) createCode=create(0,context); Require(createCode==FFX_API_RETURN_OK&&context,"RC shared path context failed");
    auto queue=RcSharedQueue(device); Require(SUCCEEDED(queue->Wait(sharedFence.Get(),30)),"RC shared path initial wait failed"); auto outputUpload=RcSharedStaging(device,sizes[1],D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ); auto counterUpload=RcSharedStaging(device,sizes[4],D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);
    auto outputReadback=RcSharedStaging(device,sizes[1],D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST); auto counterReadback=RcSharedStaging(device,sizes[4],D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);
    ComPtr<ID3D12Fence> localFence; Require(SUCCEEDED(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&localFence))),"RC shared path local fence failed"); uint64_t localValue=0;
    auto readCounts=[&]() { ComPtr<ID3D12CommandAllocator> allocator; ComPtr<ID3D12GraphicsCommandList> list; Require(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)))&&SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))),"RC shared path count list failed");
        RcTransition(list.Get(),buffers[4].gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE); list->CopyResource(counterReadback.Get(),buffers[4].gpu.Get()); RcTransition(list.Get(),buffers[4].gpu.Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE); Require(SUCCEEDED(list->Close()),"RC shared path count close failed"); ID3D12CommandList* lists[]={list.Get()}; queue->ExecuteCommandLists(1,lists); Require(SUCCEEDED(queue->Signal(localFence.Get(),++localValue)),"RC shared path count signal failed"); RcSharedWait(localFence.Get(),localValue); std::array<uint32_t,2> discovered{}; void* mapped{}; D3D12_RANGE range{0,SIZE_T(sizes[4])},empty{}; Require(SUCCEEDED(counterReadback->Map(0,&range,&mapped))&&mapped,"RC shared path count map failed"); std::memcpy(discovered.data(),mapped,sizes[4]); counterReadback->Unmap(0,&empty); inferenceCount=discovered[0]; trainingCount=discovered[1]; Require(inferenceCount&&inferenceCount<=InferenceSamples&&trainingCount==std::min(inferenceCount,TrainingSamples),"RC shared path discovered counts invalid"); }
    ; if(discoverCounts) readCounts(); const UINT initialInferenceCount=inferenceCount;
    std::vector<RcCacheOutput> outputs(InferenceSamples),baseline,post,epochStart,epochPost,changedBaseline,changedPost,changedReset,reset; std::vector<uint64_t> hashes;
    auto step=[&](uint32_t flags,UINT inference,UINT training,std::vector<RcCacheOutput>* capture) {
        for(auto& output:outputs) for(float& value:output.radiance) value=std::numeric_limits<float>::quiet_NaN(); std::array<uint32_t,2> counters={inference,training}; void* mapped{}; D3D12_RANGE empty{};
        Require(SUCCEEDED(outputUpload->Map(0,&empty,&mapped))&&mapped,"RC shared path output upload map failed"); std::memcpy(mapped,outputs.data(),sizes[1]); outputUpload->Unmap(0,nullptr);
        Require(SUCCEEDED(counterUpload->Map(0,&empty,&mapped))&&mapped,"RC shared path counter upload map failed"); std::memcpy(mapped,counters.data(),sizes[4]); counterUpload->Unmap(0,nullptr);
        ComPtr<ID3D12CommandAllocator> allocator; ComPtr<ID3D12GraphicsCommandList> list; Require(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)))&&SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))),"RC shared path step list failed");
        RcTransition(list.Get(),buffers[1].gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_DEST); RcTransition(list.Get(),buffers[4].gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_DEST);
        list->CopyResource(buffers[1].gpu.Get(),outputUpload.Get()); list->CopyResource(buffers[4].gpu.Get(),counterUpload.Get()); RcTransition(list.Get(),buffers[1].gpu.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE); RcTransition(list.Get(),buffers[4].gpu.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
        ffxDispatchDescRadianceCache dispatch{}; dispatch.header.type=FFX_API_DISPATCH_DESC_TYPE_RADIANCECACHE; dispatch.commandList=list.Get(); dispatch.predictionInputs=RcWrap(buffers[0]); dispatch.predictionOutputs=RcWrap(buffers[1]); dispatch.trainInputs=RcWrap(buffers[2]); dispatch.trainTargets=RcWrap(buffers[3]); dispatch.sampleCounters=RcWrap(buffers[4]); dispatch.flags=flags|FFX_RADIANCE_CACHE_CLEAR_ALL_COUNTERS;
        Require(api.Dispatch(&context,&dispatch.header)==FFX_API_RETURN_OK,"RC shared path dispatch failed"); RcTransition(list.Get(),buffers[1].gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE); RcTransition(list.Get(),buffers[4].gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);
        list->CopyResource(outputReadback.Get(),buffers[1].gpu.Get()); list->CopyResource(counterReadback.Get(),buffers[4].gpu.Get()); RcTransition(list.Get(),buffers[1].gpu.Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE); RcTransition(list.Get(),buffers[4].gpu.Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
        Require(SUCCEEDED(list->Close()),"RC shared path step close failed"); ID3D12CommandList* lists[]={list.Get()}; queue->ExecuteCommandLists(1,lists); Require(SUCCEEDED(queue->Signal(localFence.Get(),++localValue)),"RC shared path step signal failed"); RcSharedWait(localFence.Get(),localValue);
        D3D12_RANGE outputRange{0,SIZE_T(sizes[1])}; Require(SUCCEEDED(outputReadback->Map(0,&outputRange,&mapped))&&mapped,"RC shared path output readback map failed"); std::memcpy(outputs.data(),mapped,sizes[1]); outputReadback->Unmap(0,&empty);
        D3D12_RANGE counterRange{0,SIZE_T(sizes[4])}; Require(SUCCEEDED(counterReadback->Map(0,&counterRange,&mapped))&&mapped,"RC shared path counter readback map failed"); std::memcpy(counters.data(),mapped,sizes[4]); counterReadback->Unmap(0,&empty); Require(counters[0]==0&&counters[1]==0,"RC shared path counters not cleared");
        if(inference) { UINT finite=0,nonnegative=0; for(const auto& output:outputs) for(float value:output.radiance) { if(std::isfinite(value)) ++finite; if(std::isfinite(value)&&value>=0) ++nonnegative; } Require(finite==InferenceSamples*3&&nonnegative==InferenceSamples*3,"RC shared path inference output invalid"); if(capture) *capture=outputs; }
        else for(const auto& output:outputs) for(float value:output.radiance) Require(std::isnan(value),"RC shared path training wrote prediction output"); hashes.push_back(RcHash(outputs.data(),sizes[1]));
    };
    if(epochs==4) {
        UINT epoch=0;
        for(;;++epoch) {
            RcSharedWait(sharedFence.Get(),RcEpochProtocol::Base(epoch));
            const auto command=RcEpochProtocol::Decode(epoch,sharedFence->GetCompletedValue());
            if(command==RcEpochProtocol::Stop) break;
            Require(epoch<RcEpochProtocol::MaxEpochs&&(epoch||command==RcEpochProtocol::Reset),"RC session requires initial reset or exceeds epoch bound");
            if(discoverCounts) readCounts();
            const uint32_t resetFlag=command==RcEpochProtocol::Reset?FFX_RADIANCE_CACHE_RESET:0;
            step(resetFlag|FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&epochStart);
            for(UINT i=0;i<batches;++i) step(FFX_RADIANCE_CACHE_DISPATCH_TRAINING,0,trainingCount,nullptr);
            step(FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&epochPost);
            std::cout << "RCSESSIONEPOCH1 " << epoch << ' ' << uint64_t(command) << ' ' << inferenceCount << ' '
                << RcHash(epochStart.data(),sizes[1]) << ' ' << RcHash(epochPost.data(),sizes[1]) << '\n' << std::flush;
            Require(SUCCEEDED(queue->Signal(sharedFence.Get(),RcEpochProtocol::Ack(epoch))),"RC session acknowledgement failed");
            RcSharedWait(sharedFence.Get(),RcEpochProtocol::Ack(epoch));
        }
        Require(api.DestroyContext(&context,nullptr)==FFX_API_RETURN_OK,"RC session destroy failed"); context=nullptr;
        Require(tracked.peak>0&&tracked.peak<=budgetBytes&&!tracked.live&&!tracked.denials&&!tracked.errors&&tracked.allocations==tracked.releases,"RC session accounting failed");
        Require(device->GetDeviceRemovedReason()==S_OK,"RC session device removed");
        std::cout << "RCSESSIONEND1 " << epoch << ' ' << epoch*(2+batches) << '\n' << std::flush;
        Require(SUCCEEDED(queue->Signal(sharedFence.Get(),RcEpochProtocol::Ack(epoch))),"RC session stop acknowledgement failed");
        RcSharedWait(sharedFence.Get(),RcEpochProtocol::Ack(epoch)); return 0;
    }
    step(FFX_RADIANCE_CACHE_RESET|FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&baseline); for(UINT i=0;i<batches;++i) step(FFX_RADIANCE_CACHE_DISPATCH_TRAINING,0,trainingCount,nullptr); step(FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&post);
    if(epochs==3) { Require(SUCCEEDED(queue->Signal(sharedFence.Get(),31)),"RC live first completion signal failed"); RcSharedWait(sharedFence.Get(),32); }
    if(epochs>=2) { step(FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&epochStart); for(UINT i=0;i<batches;++i) step(FFX_RADIANCE_CACHE_DISPATCH_TRAINING,0,trainingCount,nullptr); step(FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&epochPost); }
    if(epochs==3) { Require(SUCCEEDED(queue->Signal(sharedFence.Get(),33)),"RC live stable completion signal failed"); RcSharedWait(sharedFence.Get(),34); if(discoverCounts) readCounts(); step(FFX_RADIANCE_CACHE_RESET|FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&changedBaseline); for(UINT i=0;i<batches;++i) step(FFX_RADIANCE_CACHE_DISPATCH_TRAINING,0,trainingCount,nullptr); step(FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&changedPost); step(FFX_RADIANCE_CACHE_RESET|FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&changedReset); }
    else step(FFX_RADIANCE_CACHE_RESET|FFX_RADIANCE_CACHE_DISPATCH_INFERENCE,inferenceCount,0,&reset);
    const auto& finalPost=epochs==3?changedPost:(epochs==2?epochPost:post); const auto& resetBaseline=epochs==3?changedBaseline:baseline; const auto& finalReset=epochs==3?changedReset:reset;
    uint32_t postChanged=0,epochChanged=0,changedFrameValues=0,resetChanged=0; for(UINT i=0;i<std::max(initialInferenceCount,inferenceCount);++i) for(UINT c=0;c<3;++c) { if(i<initialInferenceCount&&std::memcmp(&baseline[i].radiance[c],&post[i].radiance[c],4)) ++postChanged; if(epochs>=2&&i<initialInferenceCount&&std::memcmp(&post[i].radiance[c],&epochPost[i].radiance[c],4)) ++epochChanged; if(epochs==3&&i<inferenceCount&&std::memcmp(&changedBaseline[i].radiance[c],&changedPost[i].radiance[c],4)) ++changedFrameValues; if(i<inferenceCount&&std::memcmp(&resetBaseline[i].radiance[c],&finalReset[i].radiance[c],4)) ++resetChanged; }
    Require(postChanged==initialInferenceCount*3&&resetChanged==0&&(epochs==1||(RcHash(epochStart.data(),sizes[1])==RcHash(post.data(),sizes[1])&&epochChanged==initialInferenceCount*3))&&(epochs<3||changedFrameValues==inferenceCount*3),"RC shared path persistence/reset mismatch"); void* finalMapped{}; D3D12_RANGE finalEmpty{}; Require(SUCCEEDED(outputUpload->Map(0,&finalEmpty,&finalMapped))&&finalMapped,"RC shared path final upload map failed"); std::memcpy(finalMapped,finalPost.data(),sizes[1]); outputUpload->Unmap(0,nullptr); ComPtr<ID3D12CommandAllocator> finalAllocator; ComPtr<ID3D12GraphicsCommandList> finalList; Require(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&finalAllocator)))&&SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,finalAllocator.Get(),nullptr,IID_PPV_ARGS(&finalList))),"RC shared path final list failed"); RcTransition(finalList.Get(),buffers[1].gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_DEST); finalList->CopyResource(buffers[1].gpu.Get(),outputUpload.Get()); RcTransition(finalList.Get(),buffers[1].gpu.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE); Require(SUCCEEDED(finalList->Close()),"RC shared path final close failed"); ID3D12CommandList* finalLists[]={finalList.Get()}; queue->ExecuteCommandLists(1,finalLists); const uint64_t completion=epochs==3?35:31; Require(SUCCEEDED(queue->Signal(sharedFence.Get(),completion)),"RC shared path completion signal failed"); RcSharedWait(sharedFence.Get(),completion); Require(device->GetDeviceRemovedReason()==S_OK,"RC shared path device removed");
    Require(api.DestroyContext(&context,nullptr)==FFX_API_RETURN_OK,"RC shared path destroy failed"); context=nullptr; Require(tracked.peak>0&&tracked.peak<=budgetBytes&&!tracked.live&&!tracked.denials&&!tracked.errors&&tracked.allocations==tracked.releases,"RC shared path accounting failed");
    if(epochs==1) std::cout << "RCSHAREDSEQ1 " << RcHash(baseline.data(),sizes[1]) << ' ' << RcHash(post.data(),sizes[1]) << ' ' << RcHash(reset.data(),sizes[1]) << ' ' << postChanged << ' ' << resetChanged;
    else if(epochs==2) std::cout << "RCSHAREDEPOCH2 " << RcHash(baseline.data(),sizes[1]) << ' ' << RcHash(post.data(),sizes[1]) << ' ' << RcHash(epochStart.data(),sizes[1]) << ' ' << RcHash(epochPost.data(),sizes[1]) << ' ' << RcHash(reset.data(),sizes[1]) << ' ' << postChanged << ' ' << epochChanged << ' ' << resetChanged;
    else std::cout << "RCSHAREDLIVE3 " << RcHash(baseline.data(),sizes[1]) << ' ' << RcHash(post.data(),sizes[1]) << ' ' << RcHash(epochStart.data(),sizes[1]) << ' ' << RcHash(epochPost.data(),sizes[1]) << ' ' << RcHash(changedBaseline.data(),sizes[1]) << ' ' << RcHash(changedPost.data(),sizes[1]) << ' ' << RcHash(changedReset.data(),sizes[1]) << ' ' << postChanged << ' ' << epochChanged << ' ' << changedFrameValues << ' ' << inferenceCount << ' ' << resetChanged;
    return 0;
}

std::string RcSharedSessionParent(ID3D12Device* device,ID3D12CommandQueue* queue,ID3D12Fence* fence,RcExternalBuffer& outputBuffer,
    const std::vector<std::wstring>& args,const std::vector<HANDLE>& inherited,const std::wstring& commands,UINT count,UINT batches,UINT timeoutMs) {
    Require(!commands.empty()&&commands.size()<=16&&commands[0]==L'R'&&commands.find_first_not_of(L"RC")==std::wstring::npos,"RC session commands must be 1..16 R/C characters beginning with R");
    wchar_t executable[32768]{}; const DWORD length=GetModuleFileNameW(nullptr,executable,32768);
    Require(length&&length<32768,"RC session executable unavailable");
    RcIsolatedSession session(args,inherited,executable);
    for(UINT epoch=0;epoch<commands.size();++epoch) {
        const auto command=commands[epoch]==L'R'?RcEpochProtocol::Reset:RcEpochProtocol::Continue;
        Require(SUCCEEDED(queue->Signal(fence,RcEpochProtocol::Signal(epoch,command))),"RC session parent command failed");
        session.WaitFence(fence,RcEpochProtocol::Ack(epoch),timeoutMs);
    }
    const UINT epochs=UINT(commands.size());
    Require(SUCCEEDED(queue->Signal(fence,RcEpochProtocol::Signal(epochs,RcEpochProtocol::Stop))),"RC session stop command failed");
    session.WaitFence(fence,RcEpochProtocol::Ack(epochs),timeoutMs);
    const auto child=session.Finish(timeoutMs);
    Require(child.reaped&&!child.timedOut&&!child.overflow&&!child.exitCode&&child.error.empty(),"RC session child failed");
    std::istringstream input(child.output); std::ostringstream records; uint64_t resetHash=0,firstPost=0,lastPost=0;
    for(UINT epoch=0;epoch<epochs;++epoch) {
        std::string magic; UINT ordinal=0,command=0,populated=0; uint64_t before=0,after=0;
        Require(bool(input>>magic>>ordinal>>command>>populated>>before>>after)&&magic=="RCSESSIONEPOCH1"&&ordinal==epoch&&command==(commands[epoch]==L'R'?0u:1u)&&populated==count&&before&&after!=before,"RC session epoch report invalid");
        if(!epoch) { resetHash=before; firstPost=after; }
        Require(command?(before==lastPost):(before==resetHash&&after==firstPost),"RC session continuation/reset mismatch");
        if(epoch) records << ',';
        records << "{\"epoch\":" << epoch << ",\"reset\":" << (command?"false":"true") << ",\"start_hash\":" << before << ",\"post_hash\":" << after << '}';
        lastPost=after;
    }
    std::string magic,extra; UINT completed=0,dispatches=0;
    Require(bool(input>>magic>>completed>>dispatches)&&magic=="RCSESSIONEND1"&&completed==epochs&&dispatches==epochs*(2+batches)&&!(input>>extra),"RC session stop report invalid");
    ComPtr<ID3D12CommandAllocator> allocator; ComPtr<ID3D12GraphicsCommandList> list;
    Require(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)))&&SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))),"RC session readback list failed");
    RcTransition(list.Get(),outputBuffer.gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);
    list->CopyResource(outputBuffer.readback.Get(),outputBuffer.gpu.Get()); Require(SUCCEEDED(list->Close()),"RC session readback close failed");
    ID3D12CommandList* lists[]={list.Get()}; queue->ExecuteCommandLists(1,lists);
    const auto finalFence=RcEpochProtocol::Ack(epochs)+1;
    Require(SUCCEEDED(queue->Signal(fence,finalFence)),"RC session readback signal failed"); RcSharedWait(fence,finalFence);
    std::vector<RcCacheOutput> output(InferenceSamples); RcReadback(outputBuffer,output.data());
    Require(RcHash(output.data(),outputBuffer.bytes)==lastPost,"RC session final shared output mismatch");
    std::ostringstream report;
    report << "{\"result\":\"shared-session-pass\",\"provider_processes\":1,\"provider_contexts\":1,\"epochs\":" << epochs << ",\"provider_dispatches\":" << dispatches
        << ",\"shared_resources\":5,\"shared_fences\":1,\"allowlisted_handles\":6,\"stop_acknowledged\":true,\"child_reaped\":true,\"final_output_hash\":" << lastPost
        << ",\"records\":[" << records.str() << "]}"; return report.str();
}

std::string RcSharedPathParent(ID3D12Device* device,UINT adapterIndex,LUID luid,const std::filesystem::path& directory,const RcPathSequenceFixture& fixture,UINT batches,UINT budgetMiB,UINT timeoutMs,const std::wstring& sessionCommands=L"") {
    Require(!fixture.predictions.empty()&&fixture.predictions.size()<=InferenceSamples&&fixture.training.size()&&fixture.training.size()<=TrainingSamples&&fixture.targets.size()>=fixture.training.size()&&batches>=1&&batches<=2,"RC shared path fixture invalid");
    std::vector<RcCacheInput> predictions(InferenceSamples),training(TrainingSamples); std::vector<RcCacheOutput> outputs(InferenceSamples),targets(TrainingSamples); std::copy(fixture.predictions.begin(),fixture.predictions.end(),predictions.begin()); std::copy(fixture.training.begin(),fixture.training.end(),training.begin()); std::copy(fixture.targets.begin(),fixture.targets.begin()+fixture.training.size(),targets.begin()); for(auto& output:outputs) for(float& value:output.radiance) value=std::numeric_limits<float>::quiet_NaN(); std::array<uint32_t,2> counters={UINT(fixture.predictions.size()),0};
    const auto originalPredictions=predictions,originalTraining=training; const auto originalTargets=targets; std::array<RcExternalBuffer,5> buffers={RcCreateSharedExternalBuffer(device,sizeof(RcCacheInput)*InferenceSamples,sizeof(RcCacheInput)),RcCreateSharedExternalBuffer(device,sizeof(RcCacheOutput)*InferenceSamples,sizeof(RcCacheOutput)),RcCreateSharedExternalBuffer(device,sizeof(RcCacheInput)*TrainingSamples,sizeof(RcCacheInput)),RcCreateSharedExternalBuffer(device,sizeof(RcCacheOutput)*TrainingSamples,sizeof(RcCacheOutput)),RcCreateSharedExternalBuffer(device,sizeof(counters),sizeof(uint32_t))};
    RcUpload(buffers[0],predictions.data()); RcUpload(buffers[1],outputs.data()); RcUpload(buffers[2],training.data()); RcUpload(buffers[3],targets.data()); RcUpload(buffers[4],counters.data()); SECURITY_ATTRIBUTES security{sizeof(security),nullptr,TRUE}; std::array<RcHandle,5> resourceHandles; std::vector<HANDLE> inherited;
    for(UINT i=0;i<5;++i) { Require(SUCCEEDED(device->CreateSharedHandle(buffers[i].gpu.Get(),&security,GENERIC_ALL,nullptr,&resourceHandles[i].value)),"RC shared path handle failed"); inherited.push_back(resourceHandles[i].value); } ComPtr<ID3D12Fence> fence; RcHandle fenceHandle; Require(SUCCEEDED(device->CreateFence(0,D3D12_FENCE_FLAG_SHARED,IID_PPV_ARGS(&fence)))&&SUCCEEDED(device->CreateSharedHandle(fence.Get(),&security,GENERIC_ALL,nullptr,&fenceHandle.value)),"RC shared path fence creation failed"); inherited.push_back(fenceHandle.value);
    auto queue=RcSharedQueue(device); ComPtr<ID3D12CommandAllocator> allocator; ComPtr<ID3D12GraphicsCommandList> list; Require(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)))&&SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))),"RC shared path upload list failed"); for(auto& buffer:buffers) { list->CopyResource(buffer.gpu.Get(),buffer.upload.Get()); RcTransition(list.Get(),buffer.gpu.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE); } Require(SUCCEEDED(list->Close()),"RC shared path upload close failed"); ID3D12CommandList* uploadLists[]={list.Get()}; queue->ExecuteCommandLists(1,uploadLists); Require(SUCCEEDED(queue->Signal(fence.Get(),30)),"RC shared path parent signal failed");
    std::vector<std::wstring> args={L"--sdk-bin",directory.wstring(),L"--adapter",std::to_wstring(adapterIndex),L"--shared-path-worker-child"}; for(auto& handle:resourceHandles) args.push_back(std::to_wstring(uintptr_t(handle.value))); args.push_back(std::to_wstring(uintptr_t(fenceHandle.value))); args.push_back(std::to_wstring(luid.LowPart)); args.push_back(std::to_wstring(uint32_t(luid.HighPart))); args.push_back(std::to_wstring(fixture.predictions.size())); args.push_back(std::to_wstring(fixture.training.size())); args.push_back(std::to_wstring(batches)); args.push_back(std::to_wstring(budgetMiB)); args.push_back(sessionCommands.empty()?L"1":L"4");
    if(!sessionCommands.empty()) return RcSharedSessionParent(device,queue.Get(),fence.Get(),buffers[1],args,inherited,sessionCommands,UINT(fixture.predictions.size()),batches,timeoutMs);
    const auto child=RcRunIsolated(args,timeoutMs,false,nullptr,&inherited); Require(child.reaped&&!child.timedOut&&!child.overflow&&child.exitCode==0&&child.error.empty(),"RC shared path child failed"); std::istringstream parsed(child.output); std::string magic,extra; uint64_t baselineHash=0,postHash=0,resetHash=0; uint32_t postChanged=0,resetChanged=0; const bool fields=bool(parsed>>magic>>baselineHash>>postHash>>resetHash>>postChanged>>resetChanged); const bool noExtra=!(parsed>>extra);
    if(!(fields&&noExtra&&magic=="RCSHAREDSEQ1"&&baselineHash&&postHash!=baselineHash&&resetHash==baselineHash&&postChanged==fixture.predictions.size()*3&&resetChanged==0)) throw std::runtime_error("RC shared path child report invalid: "+child.output);
    RcSharedWait(fence.Get(),31);
    allocator.Reset(); list.Reset(); Require(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)))&&SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))),"RC shared path readback list failed"); for(auto& buffer:buffers) { RcTransition(list.Get(),buffer.gpu.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE); list->CopyResource(buffer.readback.Get(),buffer.gpu.Get()); } Require(SUCCEEDED(list->Close()),"RC shared path readback close failed"); ID3D12CommandList* readLists[]={list.Get()}; queue->ExecuteCommandLists(1,readLists); Require(SUCCEEDED(queue->Signal(fence.Get(),32)),"RC shared path readback signal failed"); RcSharedWait(fence.Get(),32); RcReadback(buffers[0],predictions.data()); RcReadback(buffers[1],outputs.data()); RcReadback(buffers[2],training.data()); RcReadback(buffers[3],targets.data()); RcReadback(buffers[4],counters.data());
    Require(std::memcmp(predictions.data(),originalPredictions.data(),predictions.size()*sizeof(predictions[0]))==0&&std::memcmp(training.data(),originalTraining.data(),training.size()*sizeof(training[0]))==0&&std::memcmp(targets.data(),originalTargets.data(),targets.size()*sizeof(targets[0]))==0,"RC shared path immutable data changed"); Require(counters[0]==0&&counters[1]==0&&RcHash(outputs.data(),outputs.size()*sizeof(outputs[0]))==postHash,"RC shared path final data invalid");
    std::ostringstream out; out << "{\"result\":\"shared-path-sequence-pass\",\"artifact_sha256\":" << QuoteBytes(fixture.artifactSha256) << ",\"populated_inference_samples\":" << fixture.predictions.size() << ",\"populated_training_samples\":" << fixture.training.size() << ",\"training_batches\":" << batches << ",\"budget_bytes\":" << uint64_t(budgetMiB)*1024*1024 << ",\"baseline_hash_fnv1a64\":" << baselineHash << ",\"post_training_hash_fnv1a64\":" << postHash << ",\"reset_hash_fnv1a64\":" << resetHash << ",\"post_changed_values\":" << postChanged << ",\"reset_changed_values\":" << resetChanged << ",\"reset_exact\":true,\"external_buffer_bytes\":716808,\"shared_resources\":5,\"shared_fences\":1,\"allowlisted_handles\":6,\"fence_values\":[30,31,32],\"child_reaped\":true,\"child_exit_code\":0,\"cpu_payload_transfer_bytes\":0}"; return out.str();
}
