"""Contract: every reference in the published docs resolves for someone who clones.

The repository is public, so a doc that points at a file the reader does not have
is a defect: it sends them looking for something that was never published. Two
classes are checkable offline and are checked here:

  1. Relative markdown links, `[label](path)`. External URLs and pure anchors are
     skipped; resolving those needs the network or a heading parser and is not
     what this guards.
  2. Backticked repository paths, `` `src/foo/bar.cpp` ``. These are how the docs
     cite implementation sites. Only paths under a known published top-level
     directory are considered, so prose that happens to contain a slash is not
     mistaken for a path.

Both are resolved against **the published file set** (`git ls-files`), not the
working tree. That is the point: the working tree also contains ignored files, so
a link to `build/...` or to a session log resolves locally and is broken for
everyone else. Checking against the working tree would silently pass.

Deliberately out of scope: references under `build/`. Those are citations of local
run artifacts (gitignored, regenerated by the tests) rather than links to
published files, and the docs describe them as such.
"""
import argparse
import os
import re
import subprocess
import sys
import urllib.parse
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1],
                    help='repository root; must be a git checkout')
args = parser.parse_args()
root = args.root.resolve()

try:
    published = subprocess.run(['git', 'ls-files'], cwd=root, capture_output=True,
                               text=True, check=True).stdout.split()
except (subprocess.CalledProcessError, FileNotFoundError) as error:
    raise SystemExit(f'this check needs a git checkout to know what is published: {error}')

published_set = set(published)
# Directory references such as `src/proxy/` are valid if any published file lives
# under them, so record every intermediate directory.
directories = set()
for path in published:
    parts = path.split('/')
    for depth in range(1, len(parts)):
        directories.add('/'.join(parts[:depth]))

TOP_LEVEL = ('src/', 'tools/', 'tests/', 'docs/', 'examples/')
docs = [path for path in published if path.endswith('.md')]
assert docs, 'no published markdown found; the published set looks wrong'

link_pattern = re.compile(r'\[[^\]]*\]\(([^)]+)\)')
path_pattern = re.compile(r'`((?:' + '|'.join(TOP_LEVEL).replace('/', r'/') + r')[A-Za-z0-9_\-./]*?)`')

link_count = path_count = 0
failures = []


def resolves(target):
    """True if target names a published file or a directory containing one."""
    if target in published_set or target in directories:
        return True
    # A directory reference may be written with a trailing slash.
    return target.rstrip('/') in directories


for doc in docs:
    text = (root / doc).read_text(encoding='utf-8', errors='ignore')
    for number, line in enumerate(text.splitlines(), 1):
        for match in link_pattern.finditer(line):
            raw = match.group(1).strip()
            if raw.startswith(('http://', 'https://', 'mailto:', '#')) or not raw:
                continue
            # Drop any fragment, then resolve relative to the containing file.
            without_fragment = urllib.parse.unquote(raw.split('#', 1)[0])
            if not without_fragment:
                continue
            link_count += 1
            relative = os.path.normpath(os.path.join(os.path.dirname(doc), without_fragment))
            relative = relative.replace('\\', '/')
            if relative.startswith('..'):
                continue  # points outside the repository; not this check's business
            if not resolves(relative):
                failures.append((doc, number, raw, relative, 'link'))
        for match in path_pattern.finditer(line):
            raw = match.group(1).rstrip('.,;:')
            if raw.startswith('build/'):
                continue
            path_count += 1
            if not resolves(raw):
                failures.append((doc, number, raw, raw, 'path reference'))

# A check that cannot fail is not a check: confirm the parser actually saw the
# corpus. These thresholds are far below the real counts (141 links, 94 paths at
# the time of writing) so they only trip if parsing broke.
assert link_count > 50, f'parsed only {link_count} relative links; the link pattern broke'
assert path_count > 50, f'parsed only {path_count} path references; the path pattern broke'

if failures:
    lines = [f'{len(failures)} reference(s) point at files that are not published:']
    for doc, number, raw, relative, kind in failures:
        lines.append(f'  {doc}:{number}  [{kind}] {raw}')
        lines.append(f'      resolves to {relative}, which no published file or directory provides')
    raise AssertionError('\n'.join(lines))

print(f'PASS every published reference resolves: {len(docs)} markdown files, '
      f'{link_count} relative links, {path_count} backticked paths, '
      f'against {len(published)} published files')
