"""Contract: the checked-in generated COM forwards match their generator.

`src/proxy/generated_observers.inc` and `src/proxy/generated_factory.inc` are
generated by `tools/generate_observers.py` from `tools/d3d9_interfaces.json` and
checked in so that building the runtime needs no Python. Nothing else verifies
that the checked-in copies are current, so a hand edit or a schema change without
regeneration compiles and ships silently. This test regenerates into a temporary
tree and requires byte identity, without touching the working tree.
"""
import argparse
import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1],
                    help='repository root containing tools/ and src/proxy/')
args = parser.parse_args()
root = args.root.resolve()

generator = root / 'tools' / 'generate_observers.py'
schema = root / 'tools' / 'd3d9_interfaces.json'
generated = ('generated_observers.inc', 'generated_factory.inc')
for required in (generator, schema, *(root / 'src' / 'proxy' / name for name in generated)):
    assert required.is_file(), f'missing required file: {required}'

# The generator resolves the repository root from its own location, so mirror the
# layout it expects rather than teaching it a root override.
work = Path(tempfile.mkdtemp(prefix='codegen-freshness-'))
try:
    (work / 'tools').mkdir()
    (work / 'src' / 'proxy').mkdir(parents=True)
    shutil.copy2(generator, work / 'tools' / generator.name)
    shutil.copy2(schema, work / 'tools' / schema.name)
    run = subprocess.run([sys.executable, str(work / 'tools' / generator.name)],
                         capture_output=True, text=True, timeout=120)
    assert run.returncode == 0, (run.stdout, run.stderr)

    # A check that cannot fail is not a check. Derive the expected override count
    # from the schema rather than trusting a magic number: every method of every
    # interface must be forwarded except the three IUnknown methods each observer
    # inherits, and every interface must contribute one identity check.
    import json
    interfaces = json.loads(schema.read_text())
    assert len(interfaces) == 20, f'unexpected interface count: {len(interfaces)}'
    device = next(i for i in interfaces if i['name'] == 'IDirect3DDevice9')
    assert len(device['methods']) == 119, f'unexpected device method count: {len(device["methods"])}'
    forwarded = sum(1 for i in interfaces for m in i['methods']
                    if m['name'] not in ('QueryInterface', 'AddRef', 'Release'))
    observer_bytes = (work / 'src' / 'proxy' / 'generated_observers.inc').read_bytes()
    assert len(observer_bytes) > 100_000, f'generated observers look truncated: {len(observer_bytes)} bytes'
    overrides = observer_bytes.count(b'STDMETHODCALLTYPE')
    assert overrides == forwarded, f'forwarded {overrides} of {forwarded} schema methods'
    identities = observer_bytes.count(b'bool Supports(')
    assert identities == len(interfaces), f'{identities} identity checks for {len(interfaces)} interfaces'
    factory_bytes = (work / 'src' / 'proxy' / 'generated_factory.inc').read_bytes()
    assert factory_bytes.count(b'TryMake<') == len(interfaces), 'generated factory is incomplete'

    stale = [name for name in generated
             if not filecmp.cmp(work / 'src' / 'proxy' / name, root / 'src' / 'proxy' / name, shallow=False)]
    if stale:
        name = stale[0]
        fresh = (work / 'src' / 'proxy' / name).read_text()
        checked = (root / 'src' / 'proxy' / name).read_text()
        line = next((i for i, (a, b) in enumerate(zip(fresh.splitlines(), checked.splitlines())) if a != b), 0)
        # Report the differing character, not a prefix that may cut before it.
        at = next((i for i, (a, b) in enumerate(zip(fresh, checked)) if a != b), min(len(fresh), len(checked)))
        window = 60
        raise AssertionError(
            f'stale generated file: {name} (first difference at line {line + 1})\n'
            f'  fresh  : ...{fresh[max(0, at - window):at]}[{fresh[at:at + window]}]...\n'
            f'  checked: ...{checked[max(0, at - window):at]}[{checked[at:at + window]}]...\n'
            f'Run: python tools/generate_observers.py  (edit the generator or '
            f'tools/d3d9_interfaces.json, never the .inc files)')
    print(f'PASS generated forwards are current with tools/generate_observers.py: '
          f'{len(interfaces)} interfaces, {overrides} forwarded methods, {len(observer_bytes)} bytes')
finally:
    shutil.rmtree(work, ignore_errors=True)
