"""Generate transparent COM forwards from checked-in Windows SDK API signatures.

Run after editing the method schema or tracing policy. Generated C++ is checked in;
building the runtime does not require Python. Signatures: Windows SDK 10.0.26100.0.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
interfaces = json.loads((root / 'tools/d3d9_interfaces.json').read_text())
by_name = {i['name']: i for i in interfaces}
out = ['// Generated by tools/generate_observers.py; edit generator/policy, not this file.\n']
for interface in interfaces:
    name = interface['name']
    ancestors = [name]
    while ancestors[-1] != 'IUnknown':
        ancestors.append(by_name[ancestors[-1]]['base'])
    out += [f'class {name}Observer final : public Observer<{name}> {{\npublic:\n',
            f'    explicit {name}Observer({name}* inner) : Observer(inner, "{name}") {{}}\n',
            '    bool Supports(REFIID iid) const noexcept override { return ' + ' || '.join(f'iid == __uuidof({n})' for n in ancestors) + '; }\n']
    for m in interface['methods']:
        if m['name'] in ('QueryInterface', 'AddRef', 'Release'):
            continue
        method, ret, args = m['name'], m['ret'], m['args']
        out.append('    ' + ret + ' STDMETHODCALLTYPE ' + method + '(' + ', '.join(a['type']+' '+a['name'] for a in args) + ') override {\n')
        call_args = []
        if method == 'CheckResourceResidency':
            out.append('        std::vector<IDirect3DResource9*> resources;\n        if(pResourceArray) { try { resources.reserve(NumResources); for(UINT32 i=0;i<NumResources;++i) resources.push_back(Unwrap(pResourceArray[i])); } catch(...) { return E_OUTOFMEMORY; } }\n')
        for a in args:
            t, n = a['type'], a['name']
            if method == 'CheckResourceResidency' and n == 'pResourceArray': call_args.append('pResourceArray ? resources.data() : nullptr')
            elif t.startswith('IDirect3D') and t.count('*') == 1: call_args.append(f'Unwrap({n})')
            else: call_args.append(n)
        # Snapshot UP memory and effective state before the native draw resets
        # stream bindings; commit only successful native calls.
        draw_calls = {
            'DrawPrimitive': 'PrimitiveType, PrimitiveCount, 0, StartVertex, 0, 0, nullptr, 0, nullptr, D3DFMT_UNKNOWN, false',
            'DrawIndexedPrimitive': 'arg0, primCount, BaseVertexIndex, startIndex, MinVertexIndex, NumVertices, nullptr, 0, nullptr, D3DFMT_UNKNOWN, true',
            'DrawPrimitiveUP': 'PrimitiveType, PrimitiveCount, 0, 0, 0, 0, pVertexStreamZeroData, VertexStreamZeroStride, nullptr, D3DFMT_UNKNOWN, false',
            'DrawIndexedPrimitiveUP': 'PrimitiveType, PrimitiveCount, 0, 0, MinVertexIndex, NumVertices, pVertexStreamZeroData, VertexStreamZeroStride, pIndexData, IndexDataFormat, true',
        }
        is_device = name.startswith('IDirect3DDevice')
        is_buffer = name in ('IDirect3DVertexBuffer9', 'IDirect3DIndexBuffer9')
        # Every observed writer/boundary gets an outcome, even when position
        # capture rejects the shader, primitive type, target or sampling quota.
        writer_device = set(draw_calls) | {'DrawRectPatch','DrawTriPatch','Clear',
            'UpdateSurface','UpdateTexture','StretchRect','ColorFill','ComposeRects',
            'GetRenderTargetData','GetFrontBufferData','Reset','ResetEx',
            'SetRenderTarget','SetDepthStencilSurface','Present','PresentEx'}
        writer_resource = not is_buffer and name in ('IDirect3DSurface9','IDirect3DBaseTexture9','IDirect3DTexture9',
            'IDirect3DCubeTexture9','IDirect3DVolumeTexture9','IDirect3DVolume9') and method in (
            'LockRect','UnlockRect','LockBox','UnlockBox','GetDC','ReleaseDC',
            'GenerateMipSubLevels','AddDirtyRect','AddDirtyBox')
        writer = (is_device and method in writer_device) or writer_resource or (name=='IDirect3DStateBlock9' and method=='Apply') or (name.startswith('IDirect3DSwapChain') and method=='Present')
        color_state = (is_device and method.startswith('Set') and not writer) or (name in ('IDirect3DBaseTexture9','IDirect3DTexture9','IDirect3DCubeTexture9','IDirect3DVolumeTexture9') and method in ('SetLOD','SetAutoGenFilterType'))
        if color_state:out.append('        auto colorState=shader::hook::BeforeColorState();\n')
        if writer:
            device = 'inner_' if is_device else 'nullptr'
            resource = 'inner_' if writer_resource and name!='IDirect3DVolume9' else 'nullptr'
            destination = {'UpdateSurface':'pDestinationSurface','UpdateTexture':'pDestinationTexture',
                'StretchRect':'pDestSurface','ColorFill':'pSurface','ComposeRects':'pDst',
                'GetRenderTargetData':'pDestSurface','GetFrontBufferData':'pDestSurface'}
            if is_device and method in destination: resource=f'Unwrap({destination[method]})'
            access={'LockRect':1,'LockBox':1,'UnlockRect':-1,'UnlockBox':-1,'GetDC':2,'ReleaseDC':-2}.get(method,0) if writer_resource else 0
            out.append(f'        auto writeEvidence=shader::hook::BeforeWriter(id,{device},{resource},"{method}",{access});\n')
        if is_device and method == 'UpdateTexture':
            out.append('        auto textureUpload=shader::hook::BeforeTextureUpload(Unwrap(pSourceTexture),Unwrap(pDestinationTexture));\n')
        if is_device and method == 'UpdateSurface':
            out.append('        auto surfaceUpload=shader::hook::BeforeSurfaceUpload(Unwrap(pSourceSurface),pSourceRect,Unwrap(pDestinationSurface),pDestPoint);\n')
        if is_device and method in draw_calls:
            out.append(f'        auto snapshot=capture::Draw(inner_, {draw_calls[method]});\n')
        if is_device and method == 'Clear':
            out.append('        auto clearEvidence=shader::hook::BeforeClear(id,inner_,Count,pRects,Flags,Color,Z,Stencil);\n')
        if is_device and method == 'DrawIndexedPrimitive':
            out.append('        auto shaderInventory=shader::inventory::BeforeDraw(id,inner_,arg0);\n')
            out.append('        auto shaderSnapshot=shader::hook::BeforeDraw(id,inner_,arg0,{BaseVertexIndex,MinVertexIndex,NumVertices,startIndex,primCount});\n')
        if is_buffer and method == 'Unlock':
            out.append('        capture::BeforeUnlock(inner_);\n')
            out.append('        shader::hook::BeforeUnlock(inner_);\n')
        if name == 'IDirect3DTexture9' and method == 'UnlockRect':
            out.append('        if(Level==0) capture::BeforeUnlock(inner_);\n')
            out.append('        shader::hook::TextureBeforeUnlock(inner_,Level);\n')
        if name == 'IDirect3DSurface9' and method == 'UnlockRect':
            out.append('        shader::hook::SurfaceTextureBeforeUnlock(inner_);\n')
        out.append('        ' + ('' if ret == 'void' else 'auto result = ') + f'inner_->{method}(' + ', '.join(call_args) + ');\n')
        if color_state:out.append('        shader::hook::AfterColorState(colorState);\n')
        if is_device and method == 'CreateTexture':
            out.append('        if(SUCCEEDED(result) && ppTexture && *ppTexture) shader::hook::TextureCreated(*ppTexture,pSharedHandle==nullptr);\n')
        if name == 'IDirect3DTexture9' and method == 'LockRect':
            out.append('        shader::hook::TextureLock(inner_,Level,pLockedRect,pRect,Flags,result);\n')
        if name == 'IDirect3DTexture9' and method == 'UnlockRect':
            out.append('        shader::hook::TextureAfterUnlock(inner_,Level,result);\n')
        if name == 'IDirect3DSurface9' and method == 'LockRect':
            out.append('        shader::hook::SurfaceTextureLock(inner_,pLockedRect,pRect,Flags,result);\n')
        if name == 'IDirect3DSurface9' and method == 'UnlockRect':
            out.append('        shader::hook::SurfaceTextureAfterUnlock(inner_,result);\n')
        if is_device and method in ('Reset','ResetEx'):
            out.append('        shader::hook::TextureReset(result);\n')
        if is_device and method in ('CreateRenderTarget','CreateRenderTargetEx'):
            private='pSharedHandle==nullptr'+(' && Usage==0' if method=='CreateRenderTargetEx' else '')
            out.append(f'        if(SUCCEEDED(result) && ppSurface && *ppSurface) shader::hook::CreatedTarget(id,*ppSurface,{private},Lockable!=FALSE);\n')
        if is_device and method in draw_calls:
            out.append('        capture::Commit(std::move(snapshot),result);\n')
        if is_device and method == 'DrawIndexedPrimitive':
            out.append('        shader::inventory::Commit(std::move(shaderInventory),result);\n')
        if is_buffer and method == 'Lock':
            out.append('        if(SUCCEEDED(result) && ppbData) shader::hook::Lock(inner_,OffsetToLock,SizeToLock,*ppbData,Flags);\n')
        if is_buffer and method == 'Unlock':
            out.append('        shader::hook::AfterUnlock(inner_,result);\n')
        if is_device and method == 'SetVertexShaderConstantF':
            out.append('        shader::hook::Constants(id,StartRegister,Vector4fCount,result);\n')
        if is_device and method == 'SetPixelShaderConstantF':
            out.append('        shader::hook::PixelConstants(id,StartRegister,Vector4fCount,result);\n')
        if is_device and method in ('Reset','ResetEx','BeginStateBlock','EndStateBlock'):
            kind=1 if method=='BeginStateBlock' else 2 if method=='EndStateBlock' else 0
            out.append(f'        shader::hook::Boundary(id,{kind},result);\n')
        if name == 'IDirect3DStateBlock9' and method == 'Apply':
            out.append('        shader::hook::Applied(result);\n')
        if is_device and method == 'ProcessVertices':
            out.append('        if(SUCCEEDED(result)) shader::hook::Invalidate(Unwrap(pDestBuffer));\n')
        if is_buffer and method == 'Lock':
            out.append('        if(SUCCEEDED(result) && ppbData) capture::BufferLock(inner_,OffsetToLock,SizeToLock,*ppbData,Flags);\n')
        if name == 'IDirect3DTexture9' and method == 'LockRect':
            out.append('        if(SUCCEEDED(result)) capture::TextureLock(inner_,Level,pLockedRect,pRect,Flags);\n')
        if (is_buffer and method == 'Unlock') or (name == 'IDirect3DTexture9' and method == 'UnlockRect'):
            out.append('        if(FAILED(result)) capture::Invalidate(inner_);\n')
        if name == 'IDirect3DSurface9' and method in ('LockRect','GetDC'):
            guard = ' && !(Flags&D3DLOCK_READONLY)' if method == 'LockRect' else ''
            out.append(f'        if(SUCCEEDED(result){guard}) capture::SurfaceWrite(inner_);\n')
        if is_device and method == 'Clear':
            out.append('        capture::Clear(inner_,Count,Flags,Color,result);\n')
            out.append('        shader::hook::AfterClear(id,std::move(clearEvidence),result);\n')
        if is_device and method in ('SetRenderTarget','SetDepthStencilSurface'):
            out.append('        shader::hook::CompositionBoundary(id,false,result);\n')
        if is_device and method in ('DrawRectPatch','DrawTriPatch','StretchRect','ColorFill','ComposeRects','UpdateSurface'):
            out.append('        capture::Unsupported(inner_,result);\n')
        if is_device and method in ('Reset','ResetEx'):
            out.append('        capture::Reset(inner_,result);\n')
        surface_dest = {'UpdateSurface':'pDestinationSurface','StretchRect':'pDestSurface','ColorFill':'pSurface','ComposeRects':'pDst','GetRenderTargetData':'pDestSurface','GetFrontBufferData':'pDestSurface'}
        if is_device and method in surface_dest:
            out.append(f'        if(SUCCEEDED(result)) capture::SurfaceWrite(Unwrap({surface_dest[method]}));\n')
        if is_device and method == 'UpdateSurface':
            out.append('        shader::hook::AfterSurfaceUpload(std::move(surfaceUpload),result);\n')
        if is_device and method == 'UpdateTexture':
            out.append('        if(SUCCEEDED(result)) capture::Invalidate(Unwrap(pDestinationTexture));\n')
            out.append('        shader::hook::AfterTextureUpload(std::move(textureUpload),result);\n')
        if name == 'IDirect3DTexture9' and method == 'AddDirtyRect':
            out.append('        shader::hook::TextureDirty(inner_,pDirtyRect,result);\n')
        if is_device and method == 'ProcessVertices':
            out.append('        if(SUCCEEDED(result)) capture::Invalidate(Unwrap(pDestBuffer));\n')
        if writer:
            out.append(f'        shader::hook::AfterWriter(writeEvidence,{"result" if ret=="HRESULT" else "S_OK"});\n')
        if is_device and method == 'DrawIndexedPrimitive':
            out.append('        shader::hook::Commit(std::move(shaderSnapshot),result);\n')
        if ret == 'HRESULT':
            for a in args:
                if a['type'].startswith('IDirect3D') and a['type'].count('*') == 2 and method != 'CheckResourceResidency':
                    t, n = a['type'].replace('*','').strip(), a['name']
                    out.append(f'        if(SUCCEEDED(result)) {{ auto wrapped=WrapReturned(__uuidof({t}),reinterpret_cast<void**>({n})); if(FAILED(wrapped)) result=wrapped; }}\n')
            if method == 'GetContainer':
                out.append('        if(SUCCEEDED(result)) { auto wrapped=WrapReturned(riid,ppContainer); if(FAILED(wrapped)) result=wrapped; }\n')
        hr = 'result' if ret == 'HRESULT' else 'S_OK'
        out.append(f'        if(TraceEnabled()) {{ try {{ Fields fields;\n')
        if method.startswith('Draw') and name.startswith('IDirect3DDevice'):
            out.append('            IDirect3DVertexShader9* vs{}; IDirect3DPixelShader9* ps{};\n            inner_->GetVertexShader(&vs); inner_->GetPixelShader(&ps);\n            fields.Value("vertex_shader_bound",vs != nullptr); fields.Value("pixel_shader_bound",ps != nullptr);\n            if(vs) vs->Release(); if(ps) ps->Release();\n')
        for a in args:
            t, n = a['type'], a['name']
            if t.startswith('IDirect3D') and t.count('*')==1:
                out.append(f'            fields.Object("{n}",{n});\n')
            elif t.startswith('IDirect3D') and t.count('*')==2 and method != 'CheckResourceResidency':
                out.append(f'            if(SUCCEEDED({hr}) && {n}) fields.Object("{n}",*{n});\n')
            elif '*' not in t and t not in ('HWND','HANDLE','HMONITOR','HDC','REFIID','REFGUID'):
                out.append(f'            fields.Value("{n}",{n});\n')
            elif ('CONST D3D' in t or t in ('CONST RECT*','D3DPRESENT_PARAMETERS*')) and t.count('*')==1:
                if t == 'D3DPRESENT_PARAMETERS*':
                    out.append(f'            if(SUCCEEDED({hr}) && {n}) {{ fields.Value("width",{n}->BackBufferWidth); fields.Value("height",{n}->BackBufferHeight); fields.Value("windowed",{n}->Windowed); }}\n')
                elif 'D3DVERTEXELEMENT9' not in t:
                    guard = ' && Count > 0' if method == 'Clear' and n == 'pRects' else ''
                    out.append(f'            if(SUCCEEDED({hr}){guard}) fields.Bytes("{n}",{n},sizeof(*{n}));\n')
        if 'Set' in method and 'ShaderConstant' in method:
            count = args[-1]['name']
            lanes = 1 if method.endswith('B') else 4
            out.append(f'            if(SUCCEEDED({hr})) fields.Bytes("constants",pConstantData,(std::min)(std::uint64_t(4096), std::uint64_t({count})*{lanes}*sizeof(*pConstantData)));\n')
        out.append(f'            Event(id,"{method}",{hr},fields.data);\n        }} catch(...) {{ Event(id,"TraceEncodingFailed",E_OUTOFMEMORY); }} }}\n')
        if method in ('Present','PresentEx'):
            out.append('        shader::hook::Presented(id,result);\n' if is_device else '        SwapPresented(inner_,result);\n')
            flags = 'dwFlags' if method == 'PresentEx' or name.startswith('IDirect3DSwapChain') else '0'
            out.append(f'        capture::Present(inner_,pSourceRect,pDestRect,hDestWindowOverride,pDirtyRegion,{flags},result);\n        EndPresent(result);\n')
        if ret != 'void': out.append('        return result;\n')
        out.append('    }\n')
    out.append('};\n')
# newline='\n' so the checked-in artifact does not depend on the host platform.
# Without it write_text emits CRLF on Windows, the freshness test compares bytes,
# and a clean checkout fails on one platform and passes on the other.
(root/'src/proxy/generated_observers.inc').write_text(''.join(out), newline='\n')
# Query the most specific interface first so inherited interfaces preserve identity.
preferred = ['IDirect3D9Ex','IDirect3DDevice9Ex','IDirect3DSwapChain9Ex','IDirect3DTexture9','IDirect3DVolumeTexture9','IDirect3DCubeTexture9']
preferred += [i['name'] for i in interfaces if i['name'] not in preferred]
def depth(name):
    return 0 if name == 'IUnknown' else 1 + depth(by_name[name]['base'])
preferred.sort(key=depth, reverse=True)
(root/'src/proxy/generated_factory.inc').write_text('// Generated by tools/generate_observers.py\n' + ''.join(f'    if(auto* e=TryMake<{n},{n}Observer>(original)) return e;\n' for n in preferred), newline='\n')
print(f'Generated {len(interfaces)} COM observers.')
